### PR TITLE
Several dependencies need updates in order to support iojs 2.x

### PR DESCRIPTION
**Pull request by dudeche**
Hello @nicks, @xiao, @kylehg,

Please review the following commits I made in branch 'ddb-update-npm-deps'.

I'm not sure if I should up the version of this in package.json as well.

e322c87c17f01ed6a165a1f2e844d9df7061d9d7 (2015-07-14 21:00:02 -0700)
Several dependencies need updates in order to support iojs 2.x

R=@nicks
R=@xiao
R=@kylehg

### CODE REVIEW

**Comment by nicks** [comment]
lgtm

**Comment by nicks** [comment]
to answer your question: yes, you'll need to bump the main package version if you want to pull this into medium2

**Comment by dudeche** [comment]
Cool -- will update.  How about publishing to npm.org?

**Comment by nicks** [comment]
you can either publish as the Medium npm account, or ping me on slack and I can publish it for you.

**Pull request merged**
