### PR TITLE
Upgrade dependencies to all use Nan>=2.0

### PR DESCRIPTION
**Pull request by chaosgame**
Hello @xiao, @sboora, @dudeche, 

Please review the following commits I made in branch 'nathan-Nan'.

7fb7dc0a3d9be2b1d4989f966c52f97ab7b8c4ce (2015-08-25 12:55:31 -0700)
Upgrade dependencies to all use Nan>=2.0

R=@xiao
R=@sboora
R=@dudeche

Test plan: 'not tested'

### CODE REVIEW

**Comment by dudeche** [comment]
lgtm

**Comment by sboora** [comment]
let's upgrade the zcache version as well.

**Comment by chaosgame** [comment]
Good call.

**Comment by xiao** [comment]
LGTM

**Pull request merged**
